### ISSUE TITLE
RestSharp, Version=106.11.7.0

### ISSUE THREAD

**Issue by EamonHetherton** [ClickSend/clicksend-csharp#5]
the latest nuget package (5.0.64) declares a dependancy on restsharp as RestSharp (>= 105.1.0) but in fact the IO.ClickSend.dll depends on RestSharp, Version=106.11.7.0 so fails at runtime without binding redirects.

**Comment by BillStrait** [comment]
Thank you for listing the correct build, you saved me some time in digging.

**Comment by EamonHetherton** [comment]
I'm glad someone is listening even if it's not the company I'm paying for the service 😠

**Comment by nesticle8bit** [comment]
I had to downgrade the version to 5.0.39, i was facing the same problem, its a shame that this company does not even listening to this Issues

**Comment by EamonHetherton** [comment]
Seems to be fixed in the latest version of the nuget package (5.0.72) BUT because of a breaking API change in restsharp from 105.1.0 -> 106.11.7 that clicksend uses, if you have directly referenced the restsharp 106.11.7 you'll get a MissingMethodException!!!

The workaround to the workaround is to remove any primary references to restsharp and take the transitive dependency from clicksend.
